baseUrl = "https://www.krayzel.net/"
title = "Home" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

googleAnalytics = "UA-129379364-1"

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "" # Enable or disable Disqus.

[params] # theme parameters
    author = "Pavel Krayzel" # Author's name.
    info = "Distributed Tech Lead & Software Architect "
    description = "Pavel Krayzel's personal website" # Site description.
    keywords = "blog,developer,personal,aws" # Site keywords.
    avatarurl = "images/avatar.png"

    footercontent = "" # Add footer content
    fixedbarContent = "" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it"

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/thumbnail.png"

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/pkrayzel/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/pkrayzel/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/pavel-krayzel-b493303b/"

# Menu links
[[menu.main]]
    name = "Books"
    weight = 100
    url  = "/books"
[[menu.main]]
    name = "Now!"
    weight = 125
    url  = "/now"
[[menu.main]]
    name = "Blog"
    weight = 200
    url  = "/posts"
[[menu.main]]
    name = "Katas"
    weight = 290
    url  = "/katas"
[[menu.main]]
    name = "About me"
    weight = 300
    url = "/about"
[[menu.main]]
    name = "CV"
    weight = 300
    url = "/work-history"