version: 2
jobs:
  build:
    docker:
      - image: library/python:3.7-alpine3.8
    steps:
      - checkout
      - run: ls
      - run: echo "Hello world"
      - run: apk --update upgrade && apk add hugo
      - run: pip install awscli
      - run: aws s3 ls s3://www.krayzel.net
