version: 2
jobs:
  build:
    docker:
      - image: library/python:3.7-alpine3.8
    steps:
      - checkout
      - run: apk --update upgrade && apk add hugo
      - run: pip install awscli
      # TODO run some smoke tests ?
      # creating distribution of website
      - run: hugo -v -d dist/
      # deploy it to s3
      - run: aws s3 sync dist/ $S3_BUCKET_NAME
      # invalidate the whole cloudfront distribution (for www.krayzel.net)
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
