version: 2
jobs:
  build:
    docker:
      - image: library/python:3.7-alpine3.8
    steps:
      - checkout
      - run: apk --update upgrade && apk add hugo
      - run: pip install awscli
      - run: $s3_bucket
      # TODO run some smoke tests ?
      # creating distribution of website
      - run: hugo -v -d dist/
      - run: aws s3 sync dist/ S3://$S3_BUCKET_NAME
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID1 --paths "/*"
      - run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID2 --paths "/*"
